import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Fuel } from 'lucide-react';
import { supabase } from '../lib/supabase';
export default function FuelSurchargePage() {
  const [rates, setRates] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Form states
  const [courier, setCourier] = useState('DHL');
  const [weekStart, setWeekStart] = useState('');
  const [weekEnd, setWeekEnd] = useState('');
  const [fuelPct, setFuelPct] = useState('');
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState('');

  useEffect(() => {
    fetchRates();
  }, []);

  const fetchRates = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from('tabel_fuel_surcharge')
      .select('*')
      .order('week_start', { ascending: false });
    
    if (data) {
      setRates(data);
    }
    setLoading(false);
  };

  const handleAdd = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setErr('');

    if (!weekStart || !weekEnd || !fuelPct) {
      setErr('Semua field harus diisi.');
      setSaving(false);
      return;
    }

    const { error } = await supabase.from('tabel_fuel_surcharge').insert([
      {
        courier,
        week_start: weekStart,
        week_end: weekEnd,
        fuel_pct: Number(fuelPct)
      } // ID generated by DB
    ]);

    if (error) {
      setErr('Gagal menyimpan: ' + error.message);
    } else {
      setWeekStart('');
      setWeekEnd('');
      setFuelPct('');
      await fetchRates();
    }
    setSaving(false);
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Yakin ingin menghapus rate ini?')) return;
    setLoading(true);
    await supabase.from('tabel_fuel_surcharge').delete().eq('id', id);
    await fetchRates();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#FFF0E2] to-[#FFC3A0] font-sans text-slate-800">
      <header className="bg-gradient-to-r from-[#3D2C44] to-[#2B1E30] text-white sticky top-0 z-10 shadow-lg">
        <div className="max-w-4xl mx-auto px-5 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-white/10 flex items-center justify-center shrink-0">
              <Fuel size={17} />
            </div>
            <div>
              <h1 className="font-bold text-base leading-tight">Fuel Surcharge</h1>
              <p className="text-[11px] text-white/50 mt-0.5">Persentase fuel surcharge mingguan DHL & FedEx</p>
            </div>
          </div>
          <Link to="/settings" className="text-xs flex items-center gap-1.5 font-semibold text-white/70 hover:text-white bg-white/5 hover:bg-white/10 border border-white/10 px-3 py-1.5 rounded-lg transition-all">
            <ArrowLeft size={13} /> Pengaturan
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="bg-white/70 backdrop-blur-md p-6 rounded-2xl shadow-sm border border-white/60 mb-6">
          <h2 className="text-base font-bold text-slate-800 mb-4">Tambah Rate</h2>
          <form onSubmit={handleAdd} className="flex flex-wrap gap-4 items-end">
            <div>
              <label className="block text-xs font-semibold text-slate-600 mb-1">Courier</label>
              <select value={courier} onChange={e => setCourier(e.target.value)} className="text-sm border border-slate-300 rounded-lg px-2 py-1.5 w-32 bg-white focus:outline-none focus:ring-2 focus:ring-[#3D2C44]/15 focus:border-[#3D2C44]">
                <option value="DHL">DHL</option>
                <option value="FEDEX">FEDEX</option>
              </select>
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-600 mb-1">Week Start (Monday)</label>
              <input type="date" value={weekStart} onChange={e => setWeekStart(e.target.value)} className="text-sm border border-slate-300 rounded-lg px-2 py-1.5 w-40 bg-white focus:outline-none focus:ring-2 focus:ring-[#3D2C44]/15 focus:border-[#3D2C44]" />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-600 mb-1">Week End (Sunday)</label>
              <input type="date" value={weekEnd} onChange={e => setWeekEnd(e.target.value)} className="text-sm border border-slate-300 rounded-lg px-2 py-1.5 w-40 bg-white focus:outline-none focus:ring-2 focus:ring-[#3D2C44]/15 focus:border-[#3D2C44]" />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-600 mb-1">Fuel Surcharge (%)</label>
              <input type="number" step="0.01" min="0" max="100" placeholder="e.g. 24.50" value={fuelPct} onChange={e => setFuelPct(e.target.value)} className="text-sm border border-slate-300 rounded-lg px-2 py-1.5 w-32 bg-white focus:outline-none focus:ring-2 focus:ring-[#3D2C44]/15 focus:border-[#3D2C44]" />
            </div>
            <button type="submit" disabled={saving} className="bg-[#3D2C44] hover:bg-[#2B1E30] text-white font-bold text-sm px-5 py-1.5 rounded-lg disabled:opacity-50 h-[34px] transition-colors shadow-sm">
              {saving ? 'Menyimpan...' : 'Tambah'}
            </button>
          </form>
          {err && <p className="text-red-500 text-xs font-bold mt-3">{err}</p>}
        </div>

        <div className="bg-white/70 backdrop-blur-md p-6 rounded-2xl shadow-sm border border-white/60">
          <h2 className="text-base font-bold text-slate-800 mb-4 border-b border-slate-100 pb-3">Riwayat Rate</h2>
          {loading ? (
            <p className="text-slate-500 text-sm">Loading rates...</p>
          ) : rates.length === 0 ? (
            <p className="text-slate-500 text-sm">Belum ada data fuel surcharge.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead className="text-xs text-[#3D2C44]/70 bg-[#3D2C44]/5 uppercase">
                  <tr>
                    <th className="px-4 py-3 font-semibold rounded-tl-lg">Courier</th>
                    <th className="px-4 py-3 font-semibold">Week Start</th>
                    <th className="px-4 py-3 font-semibold">Week End</th>
                    <th className="px-4 py-3 font-semibold">Fuel %</th>
                    <th className="px-4 py-3 font-semibold text-center rounded-tr-lg">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {rates.map(rate => (
                    <tr key={rate.id} className="hover:bg-slate-50 transition-colors">
                      <td className="px-4 py-3 font-bold text-slate-700">{rate.courier}</td>
                      <td className="px-4 py-3">{new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(rate.week_start))}</td>
                      <td className="px-4 py-3">{new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(rate.week_end))}</td>
                      <td className="px-4 py-3 font-semibold">{rate.fuel_pct}%</td>
                      <td className="px-4 py-3 text-center">
                        <button onClick={() => handleDelete(rate.id)} className="text-red-600 hover:text-red-800 text-xs font-bold bg-red-50 hover:bg-red-100 px-3 py-1 rounded-full transition-colors">
                          Hapus
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
